INSERT INTO RAFFLE (ID, AUTHOR) VALUES(1, 'TBM');
INSERT INTO RAFFLE (ID, AUTHOR) VALUES(2, 'TBM');
INSERT INTO RAFFLE (ID, AUTHOR) VALUES(3, 'TBM');
INSERT INTO RAFFLE (ID, AUTHOR) VALUES(4, 'TBM');
INSERT INTO RAFFLE (ID, AUTHOR) VALUES(5, 'TBM');
INSERT INTO RAFFLE (ID, AUTHOR) VALUES(6, 'TBM');
